export const configSiteStatic = {
  images: {
    logoHorizontal: '/LogoHorizontal.webp',
    logoVertical: '/LogoVertical.webp',
    coverBienestar: '/old/img/cover-bienestar.webp',
    coverSalud: '/old/img/cover-salud.webp',
    coverLifestyle: '/old/img/cover-lifestyle.webp',
    coverConsejos: '/old/img/cover-consejos.webp',
    coverFitness: '/old/img/cover-fitness.webp',
    coverAmor: '/old/img/cover-amor.webp',
    coverTest: '/old/img/cover-tests.webp',
    coverVos: '/old/img/cover-vos.webp',
    coverModa: '/old/img/cover-moda.webp',
    coverBelleza: '/old/img/cover-belleza.webp',
    coverRecetas: '/old/img/cover-recetas.webp',
    coverCosmic: '/old/img/cover-cosmic.webp',
  },
  icons: {
    iconoAtras: '/old/icons/IconoAtras.png',
    iconoBuscar: '/old/icons/IconoBuscar.webp',
    iconoBuscarBlack: '/old/icons/IconoBuscarBlack.webp',
    iconoHome: '/old/icons/IconoHome.webp',
    iconoFavorito: '/old/icons/IconoFavorito.webp',
    iconoVideo2: '/old/icons/IconoVideo2.webp',
    iconoBienestar: '/old/icons/IconoBienestar.webp',
    iconoModa: '/old/icons/IconoModa.webp',
    iconoBelleza: '/old/icons/IconoBelleza.webp',
    iconoRecetas: '/old/icons/IconoRecetas.webp',
    iconoAmor: '/old/icons/IconoAmorySexo.webp',
    iconoTest: '/old/icons/IconoTest.webp',
    iconoVos: '/old/icons/IconoVos.webp',
    iconoCosmic: '/old/icons/IconoCosmic.webp',
    iconoVideo: '/old/icons/IconoVideo.png',
    iconoFavoritos: '/old/icons/IconoFavoritos.webp',
    iconoSalud: '/old/icons/IconoSalud.webp',
    iconoLifestyle: '/old/icons/IconoLifestyle.webp',
    iconoConsejos: '/old/icons/IconoConsejos.webp',
    iconoFitness: '/old/icons/IconoFitness.webp',
    botonBienestar: '/old/icons/BotonBienestar.webp',
    botonModa: '/old/icons/BotonModa.webp',
    botonBelleza: '/old/icons/BotonBelleza.webp',
    botonRecetas: '/old/icons/BotonRecetas.webp',
    botonAmor: '/old/icons/BotonAmorySexo.webp',
    botonCosmic: '/old/icons/BotonCosmic.webp',
    botonVideos: '/old/icons/BotonVideos.webp',
  },
}
